### ISSUE TITLE
caches collides with the Browser API

### ISSUE THREAD

**Issue by steabert** [benjamn/optimism#492]
In one of our projects we use `@apollo/client` wich itself includes this package. After bundling as ES module, there is a top-level variable `caches` that seems to collide with the one in the Browser's API.

So, using the optimism's ES module in a browser with `type=module` doesn't work. Is that the correct behaviour?

**Comment by zolero** [comment]
I've got the same issue. I'll follow this.

**Comment by zolero** [comment]
Removing this whole line in the bundle.cjs.js and bundle.esm.js solves it for me.
https://github.com/benjamn/optimism/blob/0f177084331acd8170d16ae9ab9cfa9ad4c4f3c5/src/index.ts#L111

Afterwards we make a patch using:
```cmd
patch-package optimism
```

Hope this helps.

**Comment by steabert** [comment]
Revisiting this problem, I think I probably made the mistake of loading an ESM bundle as `text/javascript` while going back and forth between ESM and IIFE, and didn't notice that. If I load my ESM bundle as `module` it all works (as it should).
